const skillCategories = {
    Programming: [
      'JavaScript',
      'Python',
      'Java',
      'C++',
      'C#',
      'TypeScript',
      'Go',
      'Swift',
      'Kotlin',
      'PHP',
      'Ruby',
      'SQL',
      'NoSQL',
      'HTML',
      'CSS',
    ],
    WebDevelopment: [
      'React',
      'Angular',
      'Vue.js',
      'Node.js',
      'Express.js',
      'Django',
      'Ruby on Rails',
      'RESTful APIs',
      'GraphQL',
      'WebSockets',
      'Responsive Design',
      'SEO',
      'Accessibility',
    ],
    DataScience: [
      'Machine Learning',
      'Deep Learning',
      'Data Analysis',
      'Data Visualization',
      'Statistical Modeling',
      'Python (Data Science)',
      'R',
      'Tableau',
      'Power BI',
      'Big Data',
    ],
    CloudComputing: [
      'AWS',
      'Azure',
      'Google Cloud Platform',
      'Docker',
      'Kubernetes',
      'Serverless Computing',
      'DevOps',
      'CI/CD',
    ],
    MobileDevelopment: [
      'React Native',
      'Flutter',
      'Swift (iOS)',
      'Kotlin (Android)',
      'NativeScript',
      'Xamarin',
    ],
    Design: [
      'UI/UX Design',
      'User Research',
      'Interaction Design',
      'Visual Design',
      'Adobe Photoshop',
      'Adobe Illustrator',
      'Figma',
      'Sketch',
      'Wireframing',
      'Prototyping',
    ],
    ProjectManagement: [
      'Agile Methodologies',
      'Scrum',
      'Kanban',
      'Waterfall',
      'Project Planning',
      'Risk Management',
      'Team Leadership',
      'Communication',
    ],
    Communication: [
      'Written Communication',
      'Verbal Communication',
      'Presentation Skills',
      'Public Speaking',
      'Active Listening',
      'Negotiation',
    ],
    Languages: [
      'English',
      'Spanish',
      'French',
      'German',
      'Mandarin Chinese',
      'Japanese',
      'Korean',
      'Hindi',
      'Arabic',
    ],
    // ... add more categories as needed
  };